add testing step, fails automatically for now

diff --git a/.github/workflows/blue-green.yml b/.github/workflows/blue-green.yml
--- a/.github/workflows/blue-green.yml
+++ b/.github/workflows/blue-green.yml
@@ -68,7 +68,22 @@ jobs:
           CURRENT_COMMIT_ID: ${{ steps.params.outputs.current_commit_id }}
           LABEL: ${{ steps.params.outputs.label}}
 
-      # Add testing here
+      # Smoke tests
+      # This code gets index.html of the new revision that has just been deployed
+      - name: Test new revision
+        run: |
+          APP_DOMAIN=$(az containerapp env show -g cosi-103a-test -n managedEnvironment-cosi103atest-9eaf --query properties.defaultDomain -o tsv | tr -d '\r\n')
+          result=$(curl https://recipes---$LABEL.$APP_DOMAIN/api/env)
+          if [ true ] ; then
+            echo 'Test failed.'
+            az tag create --resource-id $ID --tags blueCommitId=$BLUE greenCommitId=$GREEN productionLabel=$LABEL
+            exit 1
+          fi
+        env:
+          LABEL: ${{ steps.params.outputs.production_label}}
+          GREEN: ${{ steps.params.outputs.new_green_id }}
+          BLUE: ${{ steps.params.outputs.new_blue_id }}
+          ID: ${{ steps.params.outputs.resource }}
 
       # Step to switch traffic to current commit (if tests pass)
       - name: Swap traffic
